active_modules:
  slac:
    module: EvseSlac
    config_implementation:
      main:
        device: ${PLC_IFACE}
        set_key_timeout_ms: 1000
        link_status_detection: true
        publish_mac_on_match_cnf: true
  evse_v2g:
    module: EvseV2G
    config_module:
      supported_DIN70121: false
      supported_ISO15118_2: true
      tls_security: prohibit
      device: ${PLC_IFACE}
    connections:
      security:
        - module_id: evse_security
          implementation_id: main
  evse_manager:
    module: EvseManager
    config_module:
      connector_id: 1
      connector_type: "Unknown"
      charge_mode: DC
      disable_authentication: true
      ac_hlc_enabled: false
      payment_enable_eim: true
      payment_enable_contract: false
    connections:
      slac:
        - module_id: slac
          implementation_id: main
      hlc:
        - module_id: evse_v2g
          implementation_id: charger
      bsp:
        - module_id: esp32_hal_adapter
          implementation_id: evse_board_support
      powersupply_DC:
        - module_id: esp32_hal_adapter
          implementation_id: power_supply_DC
      store:
        - module_id: kvs_file_store
          implementation_id: main
  esp32_hal_adapter:
    module: esp32_hal_adapter
    config_module:
      tty: ${ESP32_TTY}
      baud: 115200
  evse_security:
    module: EvseSecurity
    config_module:
      v2g_ca_bundle: ca/v2g/V2G_ROOT_CA.pem
  kvs_file_store:
    module: kvs_file_store
    config_module:
      path: /tmp/everest-kvs.json
